name: Terraform plan

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  terraform_pr:
    runs-on: ubuntu-latest   
    permissions:
      pull-requests: write    
    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
      with:
        path: terraform  # Check out the repository into the terraform directory

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-west-2
      env:
        AWS_PROFILE: ''

    - uses: hashicorp/setup-terraform@v3.1.2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      working-directory: terraform  # Specify the working directory for this step
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: terraform  # Specify the working directory for this step

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: terraform  # Specify the working directory for this step

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: terraform  # Specify the working directory for this step
      continue-on-error: true
