name: Terraform plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_pr:
    runs-on: ubuntu-latest   
    permissions:
      pull-requests: write    
    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
      with:
        path: terraform  # Check out the repository into the terraform directory

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-west-2

    - uses: hashicorp/setup-terraform@v3.1.2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      working-directory: terraform/terraform  # Update working directory to point to terraform/terraform
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: terraform/terraform  # Update working directory to point to terraform/terraform

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: terraform/terraform  # Update working directory to point to terraform/terraform

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: terraform/terraform  # Update working directory to point to terraform/terraform
      continue-on-error: true
    - name: Extract Plan Summary
      id: show 
      run: | 
        terraform show -no-color tfplan | grep -E 'Plan:' > plan_summary.txt 
      working-directory: terraform/terraform 
      
    - name: Post Comment 
      uses: actions/github-script@v7 
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        script: | 
          const fs = require('fs');
          const summary = fs.readFileSync('terraform/terraform/plan_summary.txt', 'utf8'); 
          const { context } = require('@actions/github'); const issue_number = context.payload.pull_request.number; 
          await github.rest.issues.createComment({ ...context.repo, issue_number, body: `### Terraform Plan Summary\n\`\`\`\n${summary}\n\`\`\`` });