name: Update README.md with current security policy

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    types: [opened, synchronize]
    
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  
jobs:
  build:
    name: update readme
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git config --global --add safe.directory /github/workspace
      - run: sed -i '/<!-- SECURITY:START -->/,/<!-- SECURITY:END -->/d' README.md

      - name: Create temporary file
        run: echo '' > temp.md

      - name: Append security content to temporary file
        run: cat SECURITY.md >> temp.md

      - name: Append temporary file to README.md
        run: cat temp.md >> README.md

      - name: Remove temporary file
        run: rm temp.md

      - name: Commit changes 
        run: | 
          git config user.email "actions@github.com" 
          git config --global user.name "githubaction"
          git pull origin main --allow-unrelated-histories --no-rebase || true
          git merge --strategy-option ours -m "Merge conflicts resolved" || git merge --strategy-option theirs -m "Merge conflicts resolved"
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
      - name: Commit changes 
        run: | 
          git add . 
          git commit -m "[GITOPS] resolved conflicts and updated README with latest changes" 
          git push --set-upstream origin readme 
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}